// This file is autogenerated, do not edit!
#pragma once
#include <million/types.hpp>

{{pointer_declarations}}

namespace components{% unless namespace == "" %}::{{namespace}}{% endunless %} {
{{components}}
} // components{% unless namespace == "" %}::{{namespace}}{% endunless %}
